# Generated by Django 4.0.4 on 2022-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_newplace_delete_explore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newname', models.CharField(max_length=100)),
                ('desc_2', models.TextField()),
                ('img_2', models.ImageField(upload_to='pictures_2')),
            ],
        ),
        migrations.DeleteModel(
            name='NewPlace',
        ),
    ]
