# Generated by Django 4.0.4 on 2022-07-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_destination_date_destination_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='day',
        ),
    ]
