# Generated by Django 4.0.4 on 2022-07-20 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_remove_destination_date_remove_destination_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
